name = input("Enter Your Name :")
print('Your Name Is ',name)
a = input("Enter First Number :")
a = int(a)
b = input("Enter Second Number :")
b = int(b)
print('Calculated sum Is ' , a+b)
print('Calculated Difference Is', a-b)
print('Calculated Product Is', a*b)
print('Calculated Quotient Is', a/b)
