m1=int(input("Enter Marks Of Student 1: "))
m2=int(input("Enter Marks Of Student 2: "))
m3=int(input("Enter Marks Of Student 3: "))
m4=int(input("Enter Marks Of Student 4: "))
m5=int(input("Enter Marks Of Student 5: "))
m6=int(input("Enter Marks Of Student 6: "))
My_list=[m1, m2, m3, m4, m5, m6]
My_list.sort()
print("SORTED MARKS: ",My_list)
E=input("Press Enter To Exit: ")
